development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pilot_development
  pool: 5
  username: root
  password: root
  port: 8889
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pilot_test
  pool: 5
  username: root
  password: root
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pilot_production
  pool: 5
  username: root
  password: root
  socket: /Applications/MAMP/tmp/mysql/mysql.sock
