development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: giftbase_development
  pool: 5
  username: root
  password: "123"

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: giftbase_test
  pool: 5
  username: root
  password: "123"

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: giftbase_development
  username: root
  password: "123"
